api_platform:
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
    patch_formats:
        json: [ 'application/json' ]
    title: Привет Илья здесь API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

