nelmio_api_doc:
  documentation:
    servers:
      - url: http://localhost:8092
        description: API over HTTP
      - url: https://api.pps.makalabox.com
        description: API over HTTPS
    info:
      title: My App
      description: This is an awesome app!
      version: 1.0.0
      x-build: #CommitHash
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []