controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute


api_login_check:
  path: /api/login


user_controllers:
  resource: ../src/Controller/user
  type: attribute
  prefix: /user


rating_controllers:
  resource: ../src/Controller/rating
  type: attribute
  prefix: /api/rating

years_controllers:
  resource: ../src/Controller/Years
  type: attribute
  prefix: /years

expert_controllers:
  resource: ../src/Controller/Expert
  type: attribute
  prefix: /api/expert